### ISSUE TITLE
Missing meta description for express example.

### ISSUE THREAD

**Issue by coolaj86** [eta-dev/eta-docs#40]
Here's what people see when they post the express example:

<img width="599" alt="Screen Shot 2022-01-27 at 11 56 50 PM" src="https://user-images.githubusercontent.com/122831/151501753-49b577de-3e23-4362-b2c2-e71964721890.png">

That sounds scary - not friendly, and not descriptive of Eta and the experience with Express.

It's missing

```html
<head>
    <meta name="description" value="something friendly and encouraging goes here">
    <meta property="og:description" content="something friendly and encouraging goes here" />
    <meta property="og:image" content="https://example.com/screenshot.png" />
    <!-- ... -->
</head>
```

**Comment by coolaj86** [comment]
I know nothing about Docusaurus. I couldn't figure out where the "html" files (or equivalent) are in the repo.

However, you probably know, and maybe this helps:
https://docusaurus.io/docs/docusaurus-core

**Comment by NaincyKumariKnoldus** [comment]
Hey @coolaj86 Can I do this please?

**Comment by coolaj86** [comment]
@NaincyKumariKnoldus I'm not a maintainer, just a reporter.

However, if you know what to do and can make a PR, I would think the maintainers would probably welcome it.

**Comment by shadowtime2000** [comment]
@coolaj86 @NaincyKumariKnoldus Hi! Correct me if I am wrong, but I don't believe Docusaurus allows for the manual editing of such descriptions, so instead the `:::danger` tag could be moved down so it appears right before the actual JS that uses Express, which would be more fitting since it doesn't really have to do with the template files.
